# Generated by Django 3.1.6 on 2021-04-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20210416_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structureblock',
            options={'verbose_name': 'Struktur-Block-Verbindung', 'verbose_name_plural': 'Struktur-Block-Verbindungen'},
        ),
    ]
