# Generated by Django 3.1.6 on 2021-04-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20210416_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structureblock',
            options={'ordering': ['structure', 'order'], 'verbose_name': 'Struktur-Block-Verbindung', 'verbose_name_plural': 'Struktur-Block-Verbindungen'},
        ),
        migrations.AddField(
            model_name='structureblock',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Sortierung'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structureblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.block', verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='structureblock',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.structure', verbose_name='Struktur'),
        ),
    ]
