# Generated by Django 3.1.6 on 2021-04-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20210416_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='blocks',
        ),
        migrations.DeleteModel(
            name='StructureBlock',
        ),
    ]
