# Generated by Django 3.1.6 on 2021-04-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0039_auto_20210422_1733'),
        ('generator', '0009_auto_20210422_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='structures',
            field=models.ManyToManyField(blank=True, to='generator.Structure'),
        ),
        migrations.AddField(
            model_name='topic',
            name='warm_up_or_filters',
            field=models.ManyToManyField(blank=True, related_name='warm_up_topics', to='trainings.Filter', verbose_name='WARM-UP ODER Filter'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='or_filters',
            field=models.ManyToManyField(blank=True, related_name='main_topics', to='trainings.Filter', verbose_name='HAUPTTEIL ODER Filter'),
        ),
    ]
