# Generated by Django 3.1.6 on 2021-04-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20210426_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='block1',
        ),
        migrations.AddField(
            model_name='structure',
            name='block1',
            field=models.ManyToManyField(related_name='structures1', to='generator.Block', verbose_name='Baustein 1'),
        ),
    ]
