# Generated by Django 3.1.6 on 2021-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_auto_20210426_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='block2',
        ),
        migrations.AddField(
            model_name='structure',
            name='block2',
            field=models.ManyToManyField(related_name='structures2', to='generator.Block', verbose_name='Baustein 2'),
        ),
        migrations.RemoveField(
            model_name='structure',
            name='block3',
        ),
        migrations.AddField(
            model_name='structure',
            name='block3',
            field=models.ManyToManyField(related_name='structures3', to='generator.Block', verbose_name='Baustein 3'),
        ),
        migrations.RemoveField(
            model_name='structure',
            name='block4',
        ),
        migrations.AddField(
            model_name='structure',
            name='block4',
            field=models.ManyToManyField(related_name='structures4', to='generator.Block', verbose_name='Baustein 4'),
        ),
        migrations.RemoveField(
            model_name='structure',
            name='block5',
        ),
        migrations.AddField(
            model_name='structure',
            name='block5',
            field=models.ManyToManyField(related_name='structures5', to='generator.Block', verbose_name='Baustein 5'),
        ),
    ]
