# Generated by Django 3.1.6 on 2021-04-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_auto_20210426_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='block4',
            new_name='blocks4',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='block5',
            new_name='blocks5',
        ),
    ]
