# Generated by Django 3.1.6 on 2021-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_auto_20210426_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='blocks5',
            field=models.ManyToManyField(blank=True, related_name='structures5', to='generator.Block', verbose_name='Baustein 5'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='phase1',
            field=models.CharField(choices=[('START', 'Warm-Up'), ('MAIN', 'Hauptteil'), ('END', 'Abschluss')], default=None, max_length=50, verbose_name='Baustein 1 Phase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structure',
            name='phase2',
            field=models.CharField(choices=[('START', 'Warm-Up'), ('MAIN', 'Hauptteil'), ('END', 'Abschluss')], default=None, max_length=50, verbose_name='Baustein 2 Phase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structure',
            name='phase3',
            field=models.CharField(choices=[('START', 'Warm-Up'), ('MAIN', 'Hauptteil'), ('END', 'Abschluss')], default=None, max_length=50, verbose_name='Baustein 3 Phase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structure',
            name='phase4',
            field=models.CharField(choices=[('START', 'Warm-Up'), ('MAIN', 'Hauptteil'), ('END', 'Abschluss')], default=None, max_length=50, verbose_name='Baustein 4 Phase'),
            preserve_default=False,
        ),
    ]
