# Generated by Django 3.1.6 on 2021-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_auto_20210427_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['ordering'], 'verbose_name': 'Baustein', 'verbose_name_plural': 'Bausteine'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['ordering'], 'verbose_name': 'Struktur', 'verbose_name_plural': 'Strukturen'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['ordering'], 'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
        migrations.AddField(
            model_name='block',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Sortierung'),
        ),
        migrations.AddField(
            model_name='structure',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Sortierung'),
        ),
        migrations.AddField(
            model_name='topic',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Sortierung'),
        ),
    ]
