# Generated by Django 3.1.6 on 2021-05-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0043_auto_20210507_1125'),
        ('users', '0016_auto_20210422_1733'),
        ('generator', '0017_auto_20210504_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('block1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_trainings1', to='generator.block', verbose_name='Block 1')),
                ('block2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_trainings2', to='generator.block', verbose_name='Block 2')),
                ('block3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_trainings3', to='generator.block', verbose_name='Block 3')),
                ('block4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_trainings4', to='generator.block', verbose_name='Block 4')),
                ('block5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_trainings5', to='generator.block', verbose_name='Block 5')),
                ('exercise1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings1', to='trainings.exercise', verbose_name='Übung 1')),
                ('exercise2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings2', to='trainings.exercise', verbose_name='Übung 2')),
                ('exercise3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings3', to='trainings.exercise', verbose_name='Übung 3')),
                ('exercise4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings4', to='trainings.exercise', verbose_name='Übung 4')),
                ('exercise5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings5', to='trainings.exercise', verbose_name='Übung 5')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings', to='generator.structure', verbose_name='Trainingsstruktur')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings', to='generator.topic', verbose_name='Thema')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_trainings', to='users.usersettings', verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['user', '-created'],
            },
        ),
    ]
