# Generated by Django 3.1.6 on 2021-05-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_auto_20210511_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='or_filters',
            new_name='main_or_filters',
        ),
    ]
