# Generated by Django 3.1.6 on 2021-05-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0044_delete_training'),
        ('generator', '0022_auto_20210511_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='youths',
            field=models.ManyToManyField(related_name='topics', to='trainings.Youth', verbose_name='Jugenden'),
        ),
    ]
