# Generated by Django 3.1.6 on 2021-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0044_delete_training'),
        ('generator', '0023_topic_youths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='youths',
            field=models.ManyToManyField(blank=True, related_name='topics', to='trainings.Youth', verbose_name='Jugenden'),
        ),
    ]
