# Generated by Django 3.1.6 on 2021-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_auto_20210511_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
    ]
