# Generated by Django 3.1.6 on 2021-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0029_auto_20210526_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['ordering'], 'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AddField(
            model_name='group',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Sortierung'),
            preserve_default=False,
        ),
    ]
