# Generated by Django 3.1.6 on 2021-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0030_auto_20210527_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pre',
            field=models.CharField(default='', max_length=80, verbose_name='Pre'),
            preserve_default=False,
        ),
    ]
