# Generated by Django 3.2.9 on 2022-06-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0032_block_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='end_or_filters',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='main_or_filters',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='start_or_filters',
        ),
    ]
