# Generated by Django 3.2.9 on 2022-06-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0048_playeramount'),
        ('generator', '0034_auto_20220621_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='exercise_amount',
            field=models.CharField(blank=True, choices=[(3, 3), (4, 4), (5, 5)], max_length=1, null=True, verbose_name='Übungsanzahl'),
        ),
        migrations.AddField(
            model_name='training',
            name='player_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.playeramount', verbose_name='Spieleranzahl'),
        ),
    ]
