# Generated by Django 3.2.9 on 2022-06-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0035_auto_20220621_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='general_or_filters',
            new_name='or_filters_1',
        ),
    ]
