# Generated by Django 3.2.9 on 2022-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0052_alter_filter_show_on_trainings_generator_step_4'),
        ('generator', '0036_rename_general_or_filters_topic_or_filters_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='or_filters_2',
            field=models.ManyToManyField(blank=True, to='trainings.Filter', verbose_name='ALTERSGRUPPE ODER Filter'),
        ),
    ]
