# Generated by Django 3.2.9 on 2022-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0038_alter_training_exercise_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('trainings', models.ManyToManyField(blank=True, to='generator.Training')),
            ],
            options={
                'verbose_name': 'Trainingsgruppe',
                'verbose_name_plural': 'Trainingsgruppen',
            },
        ),
    ]
