# Generated by Django 3.2.9 on 2022-07-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0039_traininggroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['ordering'], 'verbose_name': 'Themengruppe', 'verbose_name_plural': 'Themengruppen'},
        ),
    ]
