# Generated by Django 3.2.9 on 2022-07-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0040_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininggroup',
            options={'verbose_name': 'Trainingswoche', 'verbose_name_plural': 'Trainingswochen'},
        ),
    ]
