# Generated by Django 3.2.9 on 2022-07-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0041_alter_traininggroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininggroup',
            name='trainings',
        ),
    ]
