# Generated by Django 3.2.9 on 2022-07-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0042_remove_traininggroup_trainings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroupExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Sortierung')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.training', verbose_name='Übung')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.traininggroup', verbose_name='Trainingswoche')),
            ],
            options={
                'verbose_name': 'Trainingswoche',
                'verbose_name_plural': 'Trainingswochen',
            },
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='trainings',
            field=models.ManyToManyField(blank=True, through='generator.TrainingGroupExercise', to='generator.Training'),
        ),
    ]
