# Generated by Django 3.2.9 on 2022-07-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0043_auto_20220701_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininggroupexercise',
            options={'verbose_name': 'Trainingswochetraining', 'verbose_name_plural': 'Trainingswochetrainings'},
        ),
    ]
