# Generated by Django 3.2.9 on 2022-07-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0044_alter_traininggroupexercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininggroupexercise',
            options={'ordering': ['order'], 'verbose_name': 'Trainingswochetraining', 'verbose_name_plural': 'Trainingswochetrainings'},
        ),
    ]
