# Generated by Django 3.2.9 on 2022-07-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0046_alter_traininggroupexercise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroupexercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='generator.training', verbose_name='Übung'),
        ),
        migrations.AlterField(
            model_name='traininggroupexercise',
            name='training_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='generator.traininggroup', verbose_name='Trainingswoche'),
        ),
    ]
