# Generated by Django 3.2.9 on 2022-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0047_auto_20220701_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='trainings',
            field=models.ManyToManyField(blank=True, through='generator.TrainingGroupExercise', to='generator.Training', verbose_name='Trainings'),
        ),
    ]
