# Generated by Django 3.1.6 on 2021-03-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfilter',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
