# Generated by Django 3.1.6 on 2021-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_trainingfilter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='filters',
            field=models.ManyToManyField(to='trainings.TrainingFilter', verbose_name='Filter'),
        ),
    ]
