# Generated by Django 3.1.6 on 2021-03-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20210310_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='filters',
            field=models.ManyToManyField(blank=True, to='trainings.TrainingFilter', verbose_name='Filter'),
        ),
    ]
