# Generated by Django 3.1.6 on 2021-03-11 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20210310_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingfilter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_filters', to='trainings.filtergroup', verbose_name='Gruppe'),
        ),
    ]
