# Generated by Django 3.1.6 on 2021-03-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20210311_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtergroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='trainings.filtergroup', verbose_name='Gruppe'),
        ),
    ]
