# Generated by Django 3.1.6 on 2021-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20210311_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(null=True, upload_to='training/', verbose_name='Bild'),
        ),
    ]
