# Generated by Django 3.1.6 on 2021-03-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20210311_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training/', verbose_name='Bild'),
        ),
    ]
