# Generated by Django 3.1.6 on 2021-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_auto_20210312_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtergroup',
            options={'ordering': ['ordering'], 'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AlterModelOptions(
            name='trainingfilter',
            options={'ordering': ['ordering'], 'verbose_name': 'Filter', 'verbose_name_plural': 'Filter'},
        ),
        migrations.AddField(
            model_name='filtergroup',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingfilter',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
