# Generated by Django 3.1.6 on 2021-03-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_auto_20210319_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfilter',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Versteckt'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='ordering',
            field=models.IntegerField(verbose_name='Sortierung'),
        ),
        migrations.AlterField(
            model_name='trainingfilter',
            name='ordering',
            field=models.IntegerField(verbose_name='Sortierung'),
        ),
    ]
