# Generated by Django 3.1.6 on 2021-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_auto_20210319_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingfilter',
            name='age_group',
            field=models.ManyToManyField(to='trainings.AgeGroup', verbose_name='Altersgruppe'),
        ),
    ]
