# Generated by Django 3.1.6 on 2021-03-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_auto_20210319_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingfilter',
            old_name='age_group',
            new_name='age_groups',
        ),
    ]
