# Generated by Django 3.1.6 on 2021-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_auto_20210319_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='ordering',
            field=models.IntegerField(default=100, verbose_name='Sortierung'),
        ),
    ]
