# Generated by Django 3.1.6 on 2021-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_auto_20210321_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-created'], 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterField(
            model_name='training',
            name='image1',
            field=models.ImageField(default=None, upload_to='training/', verbose_name='Bild'),
            preserve_default=False,
        ),
    ]
