# Generated by Django 3.1.6 on 2021-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_auto_20210322_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='trainings.TrainingFilter', verbose_name='Filter'),
        ),
    ]
