# Generated by Django 3.1.6 on 2021-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0022_auto_20210325_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfilter',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
    ]
