# Generated by Django 3.1.6 on 2021-04-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0023_trainingfilter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Einstig'), ('MEDIUM', 'Fortgeschritten'), ('HARD', 'Komplex')], default='EASY', max_length=50, verbose_name='Schwierigkeit'),
        ),
    ]
