# Generated by Django 3.1.6 on 2021-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0024_training_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('ordering', models.IntegerField(verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Schwierigkeit',
                'verbose_name_plural': 'Schwierigkeiten',
                'ordering': ['ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='training',
            name='difficulty',
        ),
    ]
