# Generated by Django 3.1.6 on 2021-04-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0025_auto_20210414_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trainings.difficulty', verbose_name='Schwierigkeit'),
        ),
    ]
