# Generated by Django 3.1.6 on 2021-04-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usersettings_search'),
        ('trainings', '0029_training_focus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='Exercise',
        ),
    ]
