# Generated by Django 3.1.6 on 2021-04-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usersettings_search'),
        ('trainings', '0030_auto_20210416_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterGroup',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='AgeGroup',
            new_name='Youth',
        ),
    ]
