# Generated by Django 3.1.6 on 2021-04-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0032_auto_20210416_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-created'], 'verbose_name': 'Übung', 'verbose_name_plural': 'Übungen'},
        ),
        migrations.AlterModelOptions(
            name='youth',
            options={'ordering': ['ordering'], 'verbose_name': 'Jugend', 'verbose_name_plural': 'Jugenden'},
        ),
    ]
