# Generated by Django 3.1.6 on 2021-04-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
        ('trainings', '0034_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['name'], 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AddField(
            model_name='training',
            name='exercise1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trainings1', to='trainings.exercise', verbose_name='Übung 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='exercise2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trainings2', to='trainings.exercise', verbose_name='Übung 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='exercise3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trainings3', to='trainings.exercise', verbose_name='Übung 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='exercise4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trainings4', to='trainings.exercise', verbose_name='Übung 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='exercise5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trainings5', to='trainings.exercise', verbose_name='Übung 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='structure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='generator.structure'),
            preserve_default=False,
        ),
    ]
