# Generated by Django 3.1.6 on 2021-04-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0035_auto_20210416_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercise1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings1', to='trainings.exercise', verbose_name='Übung 1'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings2', to='trainings.exercise', verbose_name='Übung 2'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings3', to='trainings.exercise', verbose_name='Übung 3'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings4', to='trainings.exercise', verbose_name='Übung 4'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings5', to='trainings.exercise', verbose_name='Übung 5'),
        ),
    ]
