# Generated by Django 3.1.6 on 2021-04-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20210416_1555'),
        ('trainings', '0036_auto_20210416_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='generator.structure'),
        ),
        migrations.AlterField(
            model_name='training',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='generator.topic'),
        ),
    ]
