# Generated by Django 3.1.6 on 2021-04-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20210417_1710'),
        ('trainings', '0037_auto_20210416_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='generator.structure', verbose_name='Trainingsstruktur'),
        ),
        migrations.AlterField(
            model_name='training',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='generator.topic', verbose_name='Thema'),
        ),
    ]
