# Generated by Django 3.1.6 on 2021-04-26 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20210426_1001'),
        ('trainings', '0039_auto_20210422_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='block1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings1', to='generator.block', verbose_name='Block 1'),
        ),
        migrations.AddField(
            model_name='training',
            name='block2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings2', to='generator.block', verbose_name='Block 2'),
        ),
        migrations.AddField(
            model_name='training',
            name='block3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings3', to='generator.block', verbose_name='Block 3'),
        ),
        migrations.AddField(
            model_name='training',
            name='block4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings4', to='generator.block', verbose_name='Block 4'),
        ),
        migrations.AddField(
            model_name='training',
            name='block5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings5', to='generator.block', verbose_name='Block 5'),
        ),
    ]
