# Generated by Django 3.1.6 on 2021-04-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210422_1733'),
        ('trainings', '0040_auto_20210426_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='users.usersettings', verbose_name='Nutzer'),
            preserve_default=False,
        ),
    ]
