# Generated by Django 3.1.6 on 2021-05-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0042_auto_20210504_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['user', '-created'], 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
    ]
