# Generated by Django 3.1.6 on 2021-05-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0043_auto_20210507_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Training',
        ),
    ]
