# Generated by Django 3.1.6 on 2021-05-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0044_delete_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name'], 'verbose_name': 'Übung', 'verbose_name_plural': 'Übungen'},
        ),
    ]
