# Generated by Django 3.1.6 on 2021-06-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0045_auto_20210524_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='show_on_detail_bottom',
            field=models.BooleanField(default=False, verbose_name='Auf der Detailseite unten anzeigen'),
        ),
    ]
