# Generated by Django 3.2.9 on 2022-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0046_filter_show_on_detail_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='show_on_trainings_generator_step_4',
            field=models.BooleanField(default=False, verbose_name='Im Trainingsgenerator Schritt 4 anzeigen'),
        ),
    ]
