# Generated by Django 3.2.9 on 2022-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0048_playeramount'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='player_amount',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='trainings.PlayerAmount', verbose_name='Spieleranzahlen'),
        ),
    ]
