# Generated by Django 3.2.9 on 2022-06-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0049_exercise_player_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeramount',
            options={'ordering': ['amount'], 'verbose_name': 'Spieleranzahl', 'verbose_name_plural': 'Spieleranzahlen'},
        ),
    ]
