# Generated by Django 3.2.9 on 2022-06-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0050_alter_playeramount_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='player_amount',
            new_name='player_amounts',
        ),
    ]
