# Generated by Django 3.2.9 on 2022-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0051_rename_player_amount_exercise_player_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='show_on_trainings_generator_step_4',
            field=models.BooleanField(default=False, verbose_name='Im Trainingsgenerator Schritt 2 anzeigen'),
        ),
    ]
