# Generated by Django 3.2.9 on 2022-06-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0052_alter_filter_show_on_trainings_generator_step_4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['?'], 'verbose_name': 'Übung', 'verbose_name_plural': 'Übungen'},
        ),
    ]
