# Generated by Django 3.2.9 on 2022-07-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0053_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name'], 'verbose_name': 'Übung', 'verbose_name_plural': 'Übungen'},
        ),
    ]
