# Generated by Django 3.2.9 on 2022-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0055_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='show_on_trainings_generator_step_4_row_2',
            field=models.BooleanField(default=False, verbose_name='Im Trainingsgenerator Schritt 2 anzeigen auf Reihe 2'),
        ),
    ]
