# Generated by Django 3.1.6 on 2021-03-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_auto_20210319_2055'),
        ('users', '0002_auto_20210321_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settings', to='trainings.agegroup'),
        ),
    ]
