# Generated by Django 3.1.6 on 2021-03-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210321_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Benutzer Einstellung', 'verbose_name_plural': 'Benutzer Einstellungen'},
        ),
    ]
