# Generated by Django 3.1.6 on 2021-03-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210322_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='groups',
            new_name='filter_groups',
        ),
    ]
