# Generated by Django 3.1.6 on 2021-03-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_auto_20210321_1424'),
        ('users', '0008_usersettings_training_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='trainings.agegroup'),
        ),
    ]
