# Generated by Django 3.1.6 on 2021-04-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210414_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Benutzereinstellung', 'verbose_name_plural': 'Benutzereinstellungen'},
        ),
    ]
