# Generated by Django 3.1.6 on 2021-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0029_training_focus'),
        ('users', '0012_auto_20210414_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='users', to='trainings.Training'),
        ),
    ]
