# Generated by Django 3.1.6 on 2021-04-15 13:10

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0029_training_focus'),
        ('users', '0013_usersettings_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='difficulties',
            field=models.ManyToManyField(blank=True, default=apps.users.models.get_difficulties_default, related_name='users', to='trainings.Difficulty'),
        ),
    ]
