# Generated by Django 3.1.6 on 2021-05-11 11:57

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0044_delete_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_auto_20210422_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='trainings.youth', verbose_name='Altersgruppe'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='users', to='trainings.Exercise', verbose_name='Gesetzte Favoriten'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='difficulties',
            field=models.ManyToManyField(blank=True, default=apps.users.models.get_difficulties_default, related_name='users', to='trainings.Difficulty', verbose_name='Schwierigkeit'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='filter_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='trainings.Group', verbose_name='Geöffnete Gruppen'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='training_filters',
            field=models.ManyToManyField(blank=True, related_name='users', to='trainings.Filter', verbose_name='Gesetzte Filter'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
