# Generated by Django 3.1.6 on 2021-04-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'Allgemein', 'verbose_name_plural': 'Allgemein'},
        ),
    ]
