# Generated by Django 3.1.6 on 2021-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210408_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='link',
            field=models.URLField(default='https://training.vfr-garching.com', max_length=120, verbose_name='Ausbildungskonzept-Link'),
            preserve_default=False,
        ),
    ]
