# Generated by Django 3.1.6 on 2021-05-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210422_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1_info', models.TextField(verbose_name='Schritt 1 Info')),
                ('step2_info', models.TextField(verbose_name='Schritt 2 Info')),
                ('step3_info', models.TextField(verbose_name='Schritt 3 Info')),
                ('step4_info', models.TextField(verbose_name='Schritt 4 Info')),
                ('step5_info', models.TextField(verbose_name='Schritt 5 Info')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trainings',
                'verbose_name_plural': 'Trainings',
            },
        ),
    ]
