# Generated by Django 3.1.6 on 2021-05-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20210511_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundamentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Überschrift')),
                ('video1', models.CharField(blank=True, max_length=600, null=True, verbose_name='Video 1')),
                ('video2', models.CharField(blank=True, max_length=600, null=True, verbose_name='Video 2')),
            ],
            options={
                'verbose_name': 'Technik-Grundlagen',
                'verbose_name_plural': 'Technik-Grundlagen',
            },
        ),
    ]
