# Generated by Django 3.1.6 on 2021-05-31 15:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_fundamentals'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentals',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Inhalt'),
            preserve_default=False,
        ),
    ]
