# Generated by Django 3.2.9 on 2022-06-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20210604_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='legend',
            field=models.ImageField(default='/static/test.png', upload_to='', verbose_name='Legende Bild in der Übung'),
            preserve_default=False,
        ),
    ]
